blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/innocenzi/laravel-vite/discussions/new?category=q-a
    about: Ask the community for help
  - name: Request a feature
    url: https://github.com/innocenzi/laravel-vite/issues/new?labels=enhancement
    about: Share ideas for new features
  - name: Report a bug
    url: https://github.com/innocenzi/laravel-vite/issues/new
    about: Report a reproducable bug
