name: Release
on:
  push:
    branches: [main]

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install deps
        working-directory: ./npm
        run: yarn

      - name: Release
        working-directory: ./npm
        run: npx semantic-release --branches main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
